export const JobCategory = {
  AI_ENGINEER: "AI Engineer",
  BACKEND_ENGINEER: "Backend Engineer",
  FRONTEND_ENGINEER: "Frontend Engineer",
  FULL_STACK_ENGINEER: "FullStack Engineer",
  DATA_SCIENTIST: "Data Scientist",
  DEVOPS_ENGINEER: "DevOps Engineer",
  SOFTWARE_ARCHITECT: "Software Architect",
  QA_ENGINEER: "QA Engineer",
  SYSTEM_ADMINISTRATOR: "System Administrator",
  NETWORK_ENGINEER: "Network Engineer",
  SECURITY_ENGINEER: "Security Engineer",
  CLOUD_ENGINEER: "Cloud Engineer",
};

export const EmployeesCount = ["1-10", "11-20", "21-50", "51-100", "100+"];

export const Experiences = {
  FRESHER: "Fresher",
  INTERMEDIATE: "Intermediate",
  EXPERT: "Expert",
  NO_EXPERIENCE: "No Experience",
  INTERNSHIP: "Internship",
};

export const Genders = {
  MALE: "Male",
  FEMALE: "Female",
};

export const EducationDegrees = {
  HIGH_SCHOOL: "High School",
  ASSOCIATE: "Associate Degree",
  BACHELOR: "Bachelor's Degree",
  MASTER: "Master's Degree",
  DOCTORATE: "Doctorate (PhD)",
  DIPLOMA: "Diploma",
  CERTIFICATE: "Certificate",
  OTHER: "Other",
};

export default EducationDegrees;

export const Roles = {
  COMPANY: "Company",
  EMPLOYEE: "Employee",
};

export const JobPeriod = {
  FULLTIME: "FullTime",
  PARTTIME: "PartTime",
};

export const JobType = {
  INSITE: "In-Site",
  REMOTELY: "Remotely",
  HYBRID: "Hybrid",
};
export const ArabCountries = {
  ALGERIA: "Algeria",
  BAHRAIN: "Bahrain",
  COMOROS: "Comoros",
  DJIBOUTI: "Djibouti",
  EGYPT: "Egypt",
  IRAQ: "Iraq",
  JORDAN: "Jordan",
  KUWAIT: "Kuwait",
  LEBANON: "Lebanon",
  LIBYA: "Libya",
  MAURITANIA: "Mauritania",
  MOROCCO: "Morocco",
  OMAN: "Oman",
  PALESTINE: "Palestine",
  QATAR: "Qatar",
  SAUDI_ARABIA: "Saudi Arabia",
  SOMALIA: "Somalia",
  SUDAN: "Sudan",
  SYRIA: "Syria",
  TUNISIA: "Tunisia",
  UAE: "United Arab Emirates",
  YEMEN: "Yemen",
};

export const Skills = [
  "Node.js",
  "OOP",
  "RESTful APIs",
  "NLP",
  "Python",
  "SOLID principles",
  "JavaScript",
  "TypeScript",
  "React",
  "Angular",
  "Vue.js",
  "HTML5",
  "CSS3",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Go",
  "Swift",
  "Kotlin",
  "Objective-C",
  ".NET",
  "ASP.NET Core",
  "SQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Redis",
  "GraphQL",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Jenkins",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "AWS",
  "Google Cloud Platform (GCP)",
  "Microsoft Azure",
  "Firebase",
  "Terraform",
  "Nginx",
  "Apache",
  "Microservices",
  "Serverless architecture",
  "DevOps",
  "Apache Kafka",
  "RabbitMQ",
  "Elasticsearch",
  "Linux",
  "Unix",
  "Bash scripting",
  "PowerShell",
  "Command-line interface (CLI)",
  "JIRA",
  "Scrum",
  "Agile methodology",
  "TDD",
  "BDD",
  "CircleCI",
  "Travis CI",
  "Selenium",
  "Puppeteer",
  "Mocha",
  "Jest",
  "Jasmine",
  "Cypress",
  "Postman",
  "SQL Server",
  "Oracle",
  "AWS Lambda",
  "Lambda functions",
  "Elasticsearch",
  "Hadoop",
  "Spark",
  "Cloud computing",
  "WebSockets",
  "WebRTC",
  "jQuery",
  "Bootstrap",
  "Tailwind CSS",
  "SASS",
  "LESS",
  "CSS Grid",
  "Flexbox",
  "Webpack",
  "Babel",
  "Parcel",
  "Grunt",
  "Gulp",
  "Vagrant",
  "Ansible",
  "Puppet",
  "Chef",
  "Vercel",
  "Netlify",
  "WebRTC",
  "REST",
  "SOAP",
  "HATEOAS",
  "OAuth",
  "OpenID Connect",
  "JWT",
  "SAML",
  "LDAP",
  "NoSQL",
  "Graph databases",
  "Firebase",
  "Firestore",
  "Databases Design",
  "ORM",
  "Entity Framework",
  "Sequelize",
  "Mongoose",
  "SQL optimization",
  "CloudFormation",
  "Azure Functions",
  "Cloud Run",
  "Redis Caching",
  "Kafka Streams",
  "Event-driven architecture",
  "Serverless frameworks",
  "Continuous Integration",
  "Continuous Delivery",
  "Code review",
  "Monitoring & Logging",
  "Prometheus",
  "Grafana",
  "Datadog",
  "Sentry",
  "New Relic",
  "Raygun",
  "Microservices architecture",
  "API Gateway",
  "AWS S3",
  "AWS EC2",
  "Azure Blob Storage",
  "Kubernetes Service",
  "Data Analytics",
  "Business Intelligence",
  "Power BI",
  "Tableau",
  "Google Analytics",
  "Machine Learning",
  "Deep Learning",
  "Scikit-learn",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "XGBoost",
  "Pandas",
  "NumPy",
  "Scipy",
  "OpenCV",
  "spaCy",
  "Hugging Face Transformers",
  "Gensim",
  "NLTK",
  "Data Mining",
  "Data Visualization",
  "Algorithm Design",
  "Big Data",
  "ETL",
  "Data Warehousing",
  "Docker Compose",
  "RESTful design",
  "Server architecture",
  "iOS Development",
  "Android Development",
  "App deployment",
  "UX/UI Design",
  "Figma",
  "Sketch",
  "Adobe XD",
  "InVision",
  "Wireframing",
  "Prototyping",
  "User Testing",
  "Web Accessibility (a11y)",
  "Web Performance Optimization",
  "Content Delivery Network (CDN)",
  "A/B Testing",
  "SEO",
  "Web Scraping",
  "Chatbot Development",
  "Graph Databases",
  "Blockchain",
  "Cryptography",
  "Security Auditing",
];

export const Governorates = {
  ALEXANDRIA: "Alexandria",
  ASWAN: "Aswan",
  ASYUT: "Asyut",
  BEHERA: "Beheira",
  BENI_SUEF: "Beni Suef",
  CAIRO: "Cairo",
  DAKAHLIYA: "Dakahliya",
  DAMIETTA: "Damietta",
  FAYOUM: "Fayoum",
  GHARBIA: "Gharbia",
  GIZA: "Giza",
  ISMAILIA: "Ismailia",
  KAFR_EL_SHEIKH: "Kafr El-Sheikh",
  LUXOR: "Luxor",
  MATROUH: "Matrouh",
  MINYA: "Minya",
  MONUFIA: "Monufia",
  NEW_VALLEY: "New Valley",
  NORTH_SINAI: "North Sinai",
  PORT_SAID: "Port Said",
  QALYUBIA: "Qalyubia",
  QENA: "Qena",
  RED_SEA: "Red Sea",
  SHARQIYA: "Sharqiya",
  SOHAG: "Sohag",
  SOUTH_SINAI: "South Sinai",
  SUEZ: "Suez",
};

export const ApplicationStatus = {
  PENDING: "Pending",
  ACCEPTED: "Accepted",
  REJECTED: "Rejected",
};

export const ApplicationResponse = {
  ACCEPT: "Accept",
  REJECT: "Reject",
};

export const Reactions = {
  LIKE: "Like",
  LOVE: "Love",
  FUNNY: "Funny",
  CELEBRATE: "Celebrate",
};

export const CommunityEntities = {
  POST: "Post",
  COMMENT: "Comment",
};
