export const JobCategory = {
  AI_ENGINEER: "AI Engineer",
  BACKEND_ENGINEER: "Backend Engineer",
  FRONTEND_ENGINEER: "Frontend Engineer",
  FULL_STACK_ENGINEER: "FullStack Engineer",
  DATA_SCIENTIST: "Data Scientist",
  DEVOPS_ENGINEER: "DevOps Engineer",
  SOFTWARE_ARCHITECT: "Software Architect",
  QA_ENGINEER: "QA Engineer",
  SYSTEM_ADMINISTRATOR: "System Administrator",
  NETWORK_ENGINEER: "Network Engineer",
  SECURITY_ENGINEER: "Security Engineer",
  CLOUD_ENGINEER: "Cloud Engineer",
};

export const EmployeesCount = ["1-10", "11-20", "21-50", "51-100", "100+"];

export const Experiences = {
  FRESHER: "Fresher",
  INTERMEDIATE: "Intermediate",
  EXPERT: "Expert",
  NO_EXPERIENCE: "No Experience",
  INTERNSHIP: "Internship",
};

export const Genders = {
  MALE: "Male",
  FEMALE: "Female",
};

export const EducationDegrees = {
  HIGH_SCHOOL: "High School",
  ASSOCIATE: "Associate Degree",
  BACHELOR: "Bachelor's Degree",
  MASTER: "Master's Degree",
  DOCTORATE: "Doctorate (PhD)",
  DIPLOMA: "Diploma",
  CERTIFICATE: "Certificate",
  OTHER: "Other",
};

export default EducationDegrees;

export const Roles = {
  COMPANY: "Company",
  EMPLOYEE: "Employee",
};

export const JobPeriod = {
  FULLTIME: "FullTime",
  PARTTIME: "PartTime",
};

export const JobType = {
  INSITE: "In-Site",
  REMOTELY: "Remotely",
  HYBRID: "Hybrid",
};
export const ArabCountries = {
  ALGERIA: "Algeria",
  BAHRAIN: "Bahrain",
  COMOROS: "Comoros",
  DJIBOUTI: "Djibouti",
  EGYPT: "Egypt",
  IRAQ: "Iraq",
  JORDAN: "Jordan",
  KUWAIT: "Kuwait",
  LEBANON: "Lebanon",
  LIBYA: "Libya",
  MAURITANIA: "Mauritania",
  MOROCCO: "Morocco",
  OMAN: "Oman",
  PALESTINE: "Palestine",
  QATAR: "Qatar",
  SAUDI_ARABIA: "Saudi Arabia",
  SOMALIA: "Somalia",
  SUDAN: "Sudan",
  SYRIA: "Syria",
  TUNISIA: "Tunisia",
  UAE: "United Arab Emirates",
  YEMEN: "Yemen",
};

export const Skills = [
  "JavaScript",
  "TypeScript",
  "React",
  "HTML5",
  "CSS3",
  "Flexbox",
  "CSS Grid",
  "Tailwind CSS",
  "Bootstrap",
  "SASS",
  "Webpack",
  "Babel",
  "Vue.js",
  "Angular",
  "Responsive Design",
  "Web Accessibility (a11y)",
  "Web Performance Optimization",
  "SEO",
  "Figma",
  "Prototyping",
  "Jest",
  "Cypress",
  "Selenium",
  "Puppeteer",
  "Node.js",
  "Express.js",
  "RESTful APIs",
  "GraphQL",
  "Python",
  "Java",
  "C#",
  "Go",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Sequelize",
  "Mongoose",
  "Entity Framework",
  "Microservices architecture",
  "Serverless architecture",
  "Docker",
  "Kubernetes",
  "Terraform",
  "AWS",
  "Google Cloud Platform (GCP)",
  "Microsoft Azure",
  "CI/CD",
  "Git",
  "API Gateway",
  "OAuth",
  "JWT",
  "CloudFormation",
  "Azure Functions",
  "Monitoring & Logging",
  "Prometheus",
  "Datadog",
  "Python",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "SciPy",
  "OpenCV",
  "NLP",
  "spaCy",
  "Hugging Face Transformers",
  "NLTK",
  "Gensim",
  "XGBoost",
  "Data Mining",
  "Big Data",
  "Spark",
  "Hadoop",
  "ETL",
  "Data Warehousing",
  "Data Visualization",
  "Tableau",
  "Power BI",
  "Model Deployment",
  "FastAPI",
  "Flask",
  "Docker",
  "Azure ML",
  "MLOps",
  "Algorithm Design",
  "Statistics",
];

export const Governorates = {
  ALEXANDRIA: "Alexandria",
  ASWAN: "Aswan",
  ASYUT: "Asyut",
  BEHERA: "Beheira",
  BENI_SUEF: "Beni Suef",
  CAIRO: "Cairo",
  DAKAHLIYA: "Dakahliya",
  DAMIETTA: "Damietta",
  FAYOUM: "Fayoum",
  GHARBIA: "Gharbia",
  GIZA: "Giza",
  ISMAILIA: "Ismailia",
  KAFR_EL_SHEIKH: "Kafr El-Sheikh",
  LUXOR: "Luxor",
  MATROUH: "Matrouh",
  MINYA: "Minya",
  MONUFIA: "Monufia",
  NEW_VALLEY: "New Valley",
  NORTH_SINAI: "North Sinai",
  PORT_SAID: "Port Said",
  QALYUBIA: "Qalyubia",
  QENA: "Qena",
  RED_SEA: "Red Sea",
  SHARQIYA: "Sharqiya",
  SOHAG: "Sohag",
  SOUTH_SINAI: "South Sinai",
  SUEZ: "Suez",
};

export const ApplicationStatus = {
  PENDING: "Pending",
  ACCEPTED: "Accepted",
  REJECTED: "Rejected",
};

export const ApplicationResponse = {
  ACCEPT: "Accept",
  REJECT: "Reject",
};

export const Reactions = {
  LIKE: "Like",
  LOVE: "Love",
  FUNNY: "Funny",
  CELEBRATE: "Celebrate",
};

export const CommunityEntities = {
  POST: "Post",
  COMMENT: "Comment",
};
